chore: empty array check

diff --git a/.github/actions/check-variables/action.yaml b/.github/actions/check-variables/action.yaml
--- a/.github/actions/check-variables/action.yaml
+++ b/.github/actions/check-variables/action.yaml
@@ -13,7 +13,11 @@ runs:
     run: |
       variables=${{ inputs.variables }}
       json_array=$(echo "\"$variables\"" | jq -c 'split(",")')
-      mapfile -t variables_array < <(echo "$json_array" | jq -r '.[]')   
+      mapfile -t variables_array < <(echo "$json_array" | jq -r '.[]')
+      if [ ${#variables_array[@]} -eq 0 ]; then
+        echo "❌ Input is missing!"
+        exit 1
+      fi   
       for item in "${variables_array[@]}"; do
         echo "Variable: [$item]"
         if [ -z $item ]; then
