fix sintaxe

diff --git a/.github/actions/create-role-service-account/action.yaml b/.github/actions/create-role-service-account/action.yaml
--- a/.github/actions/create-role-service-account/action.yaml
+++ b/.github/actions/create-role-service-account/action.yaml
@@ -54,8 +54,31 @@ runs:
           echo "role_exists=false" >> $GITHUB_OUTPUT
         fi
 
-  - name: Buscar OIDC provider
+  # - name: Buscar OIDC provider
+  #   shell: bash
+  #   run: |
+  #     INPUT_STRING=${{ inputs.role }}
+  #     echo "env - $INPUT_STRING"
+  #     ENVIRONMENT="${INPUT_STRING##*-}"
+  #     AWS_REGION="us-east-1"
+
+  #     OIDC_PROVIDER=$(aws secretsmanager get-secret-value \
+  #         --secret-id "oidc_provider/$ENVIRONMENT" \
+  #         --region "$AWS_REGION" \
+  #         --query SecretString \
+  #         --output text)
+
+  #     if [ $? -ne 0 ]; then
+  #         echo "Failed to retrieve secret"
+  #         exit 1
+  #     fi
+
+  #     export OIDC_PROVIDER
+  #     echo "Secret fetched successfully."
+
+  - name: Criar role
     shell: bash
+    if: steps.check-role.outputs.role_exists == 'false'
     run: |
       INPUT_STRING=${{ inputs.role }}
       echo "env - $INPUT_STRING"
@@ -75,11 +98,6 @@ runs:
 
       export OIDC_PROVIDER
       echo "Secret fetched successfully."
-
-  - name: Criar role
-    shell: bash
-    if: steps.check-role.outputs.role_exists == 'false'
-    run: |
       aws iam create-role --role-name "${{ inputs.role }}" --assume-role-policy-document '{
       "Version": "2012-10-17",
       "Statement": [
